### ISSUE TITLE
Add "Sum of 2 numbers" program in Python 

### ISSUE THREAD

**Issue by imdebamrita** [imdebamrita/ModelFlow#1]
Add "Sum of 2 numbers" program in Python 

- With User Input

**Comment by sayan-1210** [comment]
I want resolve this issue.
Please assign me.

**Comment by Pratik-Jodgudri** [comment]
I have created a pull request for this issue.  Please review it. @imdebamrita

**Comment by imdebamrita** [comment]
This issue is assigned to @sayan-1210 and may be he is working on it...so sorry at this point I can not accept your PR. 
Please create the PR on other issues I will definitely can accept. @Pratik-Jodgudri

**Comment by Pratik-Jodgudri** [comment]
Ok sorry for that.

**Comment by imdebamrita** [comment]
It's ok @Pratik-Jodgudri

**Comment by imdebamrita** [comment]
Thank you @sayan-1210 👍👍
