### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by imdebamrita** [imdebamrita/ModelFlow#12]
Make a good README.md

- Understand the repo structure and build a nice visualization of that. 
- Give general information about contributing in the repo (which is already written in the [CONTRIBUTING.md](https://github.com/imdebamrita/ModelFlow/blob/main/CONTRIBUTING.md) ).
- Make it a bit attractive.

**Comment by gautamb02** [comment]
heyy 

Assign this one to me !!

**Comment by nikhilnrr** [comment]
Hey @gautam-bhagat , could you please assign this issue to me? It'd be freat to start with this one :)

**Comment by imdebamrita** [comment]
@nikhilnrr we are following the first come first serve approach, so try to contribute in other issues or create new issues.
