### ISSUE TITLE
There is no Random Forest Classifier model under Machine Learning. 

### ISSUE THREAD

**Issue by Pratik-Jodgudri** [imdebamrita/ModelFlow#2]
There is no Random Forest Classifier model under Machine Learning.

**Comment by Pratik-Jodgudri** [comment]
I would like to add a model. Can you assign it to me? @imdebamrita

**Comment by Pratik-Jodgudri** [comment]
I have the model. Please review the pull request. @imdebamrita

**Comment by imdebamrita** [comment]
Thank you @Pratik-Jodgudri 👍👍
